### ISSUE TITLE
Replace Sketch tool in Editing

### ISSUE THREAD

**Issue by cob222** [Esri/arcgis-pro-sdk-community-samples#24]
Replace sketch not working any more. The command is in the sketch dropdown but doesn't do anything. Tried it on two computers same thing. It used to work and I haven't changed anything with the system. I deleted, downloaded the zip and started over with the same result. What gives? Thanks ,cob

**Comment by Wolf-K** [comment]
Hi cob,
 I just tried the sample (using the data and instructions from the readme.md) and was able to run the add-in with no problems.  I am using ArcGIS Pro 1.4.1.  Also you can set a break point on the OnClick method in ReplaceSketch.cs, it should hit that breakpoint when you click on the "replace sketch" entry in the context menu.  I was able to split the polygon using the intersecting line feature.  Once you step through the OnClick method you should see where the problem is.  Below a screen shot of my result:

![image](https://cloud.githubusercontent.com/assets/5561398/25677648/7bb95e58-2fe2-11e7-9461-d66c3a488cbb.png)

**Comment by cob222** [comment]
You mean in visual studio? I'm not much of a programmer. It used to just
work. What I'm trying to do is create a feature in a polygon feature class
based on selected line features. Are you able to do that? This is due to my
folks having arc pro basic which doesn't have feature to polygon. And these
are very wiggly GPS lines that are difficult to trace - you have to zoom in
and trace one little section at a time. Should I be using create or modify
features? Polygon or autocomplete sketch tool? Thanks for your response -
cob

**Comment by Wolf-K** [comment]
Thanks for the clarification.  I tried the tool using ArcGIS Pro basic and it works as documented.  However, the documentation doesn't describe the workflow that you described in your comment above.  Let me first explain what the 'replace sketch' sample does: it allows you to use an existing feature (for example a line) instead of a manually hand-digitized sketch.  Hence the name: replace sketch - it replaces a manual input sketch (if any) with the selected feature by right clicking and selecting the 'replace sketch' menu option.  Note that you have to use snapping because the line has to be found within 5 pixels from the mouse click.  So the selected line is now entered as your (normally) manually input sketch.  So the documentation shows me modifying a polygon using the "Split Tool" by sketching a line over the selected polygon: 1) I can manually sketch a line that intersects that polygon, or 2) i can right click an existing line feature and click the "replace sketch" menu option.  Either way when I complete the sketch Pro will take the sketched line and split the polygon accordingly.  I think what you are looking for is a tool that takes GPS lines (or points) and uses those lines (or points) to create a polygon, this sample doesn't do that.  However, there are other samples that would probably show you how to make a polygon out of a selected line feature.  I will look through the samples, check, and get you a link if that is what you are looking for.

**Comment by cob222** [comment]
Thanks Wolfgang, but I have actually used the tool for this before - it
traced around the entire line and held the sketch status at the last
closing point. Then I could just finish sketch and voila. But it's not
working now so I'd be grateful for another solution if you can find it. The
options with basic license are limited. Thanks, cob

**Comment by Wolf-K** [comment]
I tried a slightly different workflow and this seemed to work:
1) I have a line feature (single feature with multiple segments)
![image](https://cloud.githubusercontent.com/assets/5561398/25726370/7f7ba590-30bf-11e7-8d92-149f162de886.png)
2) I start editing using Create Polygon using the "Autocomplete Polygon" 
![image](https://cloud.githubusercontent.com/assets/5561398/25726397/adfd33a2-30bf-11e7-9d89-d7ef467f444c.png)
3) right click on my line - somehow I have to try this twice in some cases - and select the Replace Sketch
![image](https://cloud.githubusercontent.com/assets/5561398/25726423/cdbb6240-30bf-11e7-81eb-6918c12715e0.png)
4) I see the line with nodes
![image](https://cloud.githubusercontent.com/assets/5561398/25726445/ddce0778-30bf-11e7-81d3-77113645edf4.png)
5) I finish the sketch (auto complete somehow didn't work but double click on the start node did).
![image](https://cloud.githubusercontent.com/assets/5561398/25726474/084760c6-30c0-11e7-9506-089bc60f435c.png)
