### ISSUE TITLE
ExportWeb3DObjectResource fails to export 3D objects

### ISSUE THREAD

**Issue by LG-Spatial** [Esri/arcgis-pro-sdk-community-samples#29]
Downloaded source data, tool only export 'trees' features and fails on the others. then  arcPro 2.0 crashes.

**Comment by UmaHarano** [comment]
Hi,

When you use `ExportWeb3DObjectResource` method, the export will fail if it is a restricted symbol.  This is because many symbols have licensing constraints and cannot be shared to the web.  

The Esri System styles do not have these restrictions so you should be able to export any 3D Symbols you use from here.

Thanks
Uma
