### ISSUE TITLE
MapToolWithCustomPopup <empty>

### ISSUE THREAD

**Issue by jbowdeny2k** [Esri/arcgis-pro-sdk-community-samples#34]
The screen shot you have with this example show the header with "U.S. States (Generalized) - Oregon".  When I run the tool it shows up as "U.S. States (Generalized) - \<empty\>". But in the [guide](https://github.com/Esri/arcgis-pro-sdk/wiki/ProGuide-Custom-Pop-ups) it also shows up as \<empty\>.  I don't see any way to change the header in the custom code so I would assume it should use the layer default display column.

**Comment by Wolf-K** [comment]
It turns out what you are seeing is a combination of a bug and a following re-design of the UI.  The bug was that the 'displayed' record (using the display field) sometimes showed &lt;empty&gt; instead of the display field's content.  In 2.4 the map exploration team redesigned the pop-up look and feel to look more like the default layer pop-up.  However, the <empty> bug was still not fixed in 2.4. 
![image](https://user-images.githubusercontent.com/5561398/63374837-585a5780-c326-11e9-8795-7377b644f72f.png)
 In 2.5 everything works as designed.  We will update the ProConcept documentation with the next release to match 2.5 functionality.
![image](https://user-images.githubusercontent.com/5561398/63374863-67410a00-c326-11e9-8162-855eafe36b21.png)

**Comment by jbowdeny2k** [comment]
That's what I suspected, but I wanted to make sure it wasn't something I was doing wrong.  Thanks
